"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { FORM_CONFIG, FORM_TYPES } from "@/lib/claim-forms";

type Check={label:string;passed:boolean;reason:string}; type Claim={id:string;formType:string;amount:string|number;purpose:string;createdAt:string;stages:{id:string;seq:number;stageName:string;officerName:string|null;officerDesignation:string|null;office:string|null;enteredAt:string;exitedAt:string|null;escalatedFrom:string|null}[]};
export default function ClaimsWorkspace({ eligibility, claims }: { eligibility: Record<string,Check[]>; claims: Claim[] }) {
 const [tab,setTab]=useState<"raise"|"track">("raise"); const [form,setForm]=useState<string|null>(null); const [step,setStep]=useState(1); const [fields,setFields]=useState<Record<string,string>>({}); const [docs,setDocs]=useState<Record<string,{filename:string;sizeBytes:number}>>({}); const [toast,setToast]=useState(""); const router=useRouter();
 const cfg=form?FORM_CONFIG[form as keyof typeof FORM_CONFIG]:null; const checks=form?eligibility[form]||[]:[]; const valid=checks.every(c=>c.passed);
 const submit=async()=>{const r=await fetch("/api/claims",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({formType:form,fields,documents:docs})});const d=await r.json();if(!r.ok){setToast(d.error||"Unable to submit");return;}setToast("Claim submitted successfully.");setForm(null);setStep(1);setFields({});setDocs({});setTab("track");router.refresh();};
 return <div className="claims-page"><div className="claims-tabs"><button className={tab==="raise"?"tab-active":""} onClick={()=>setTab("raise")}>Raise a claim</button><button className={tab==="track"?"tab-active":""} onClick={()=>setTab("track")}>Track claims</button></div>{toast&&<div className="claim-toast">{toast}<button onClick={()=>setToast("")}>×</button></div>}
 {tab==="raise"&&!form&&<section><h1>Choose a claim</h1><p className="muted">Select the request that best describes what you need.</p><div className="claim-form-grid">{FORM_TYPES.map(t=>{const c=FORM_CONFIG[t];return <button className="claim-form-card" key={t} onClick={()=>{setForm(t);setStep(1)}}><span className="radio-dot"/><h2>{c.title}</h2><p>{c.plainEnglishOneLiner}</p><small>{c.whoItsFor}</small></button>})}</div></section>}
 {tab==="raise"&&form&&cfg&&<section className="claim-wizard"><button className="back-link" onClick={()=>setForm(null)}>← Choose another claim</button><h1>{cfg.title}</h1><div className="wizard-steps"><span className={step>=1?"current":""}>1 Eligibility</span><span className={step>=2?"current":""}>2 Details</span><span className={step>=3?"current":""}>3 Documents & submit</span></div>{step===1&&<div className="wizard-panel"><p>{cfg.whoItsFor}</p>{checks.map(c=><div className={c.passed?"eligibility-pass":"eligibility-fail"} key={c.label}><b>{c.passed?"✓":"!"}</b><span>{c.label}<small>{c.passed?"Passed":c.reason}</small></span></div>)}<button className="primary-button" disabled={!valid} onClick={()=>setStep(2)}>Continue</button></div>}{step===2&&<div className="wizard-panel"><div className="claim-fields">{cfg.fields.map(f=><label key={f.key}>{f.label}{f.required&&" *"}{f.type==="select"?<select value={fields[f.key]||""} onChange={e=>setFields({...fields,[f.key]:e.target.value})}><option value="">Select</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type} value={fields[f.key]||""} onChange={e=>setFields({...fields,[f.key]:e.target.value})}/>} {f.helpText&&<small>{f.helpText}</small>}</label>)}</div><button className="primary-button" disabled={cfg.fields.some(f=>f.required&&!fields[f.key])} onClick={()=>setStep(3)}>Continue</button></div>}{step===3&&<div className="wizard-panel"><p>Upload the documents for this request. Files stay as filename and size in this demo.</p>{cfg.requiredDocs.map(d=><label className="doc-row" key={d.key}><span>{docs[d.key]?"✓":"○"}</span>{d.label}{d.required&&" *"}<input type="file" onChange={e=>{const f=e.target.files?.[0];if(f)setDocs({...docs,[d.key]:{filename:f.name,sizeBytes:f.size}})}}/>{docs[d.key]&&<small>{docs[d.key].filename}</small>}</label>)}<div className="review-box"><b>Review</b><p>{cfg.title} · ₹{Number(fields.amount||0).toLocaleString("en-IN")}</p></div><button className="primary-button" disabled={cfg.requiredDocs.some(d=>d.required&&!docs[d.key])} onClick={submit}>Submit claim</button></div>}</section>}
 {tab==="track"&&<Track claims={claims} onToast={setToast}/>}</div>;
}
function Track({claims,onToast}:{claims:Claim[];onToast:(s:string)=>void}){const [open,setOpen]=useState<string|null>(null);const [busy,setBusy]=useState<string|null>(null);if(!claims.length)return <div className="claim-empty"><div className="claim-empty-illustration">✓</div><h1>No requests or claims</h1><p>Your submitted requests will appear here with a clear, step-by-step timeline.</p></div>;return <section><h1>Track claims</h1>{claims.map(claim=>{const current=claim.stages.find(s=>!s.exitedAt);const days=(s:{enteredAt:string;exitedAt:string|null})=>Math.max(0,Math.floor((new Date(s.exitedAt||Date.now()).getTime()-new Date(s.enteredAt).getTime())/86400000));return <article className="claim-timeline-card" key={claim.id}><div className="claim-summary"><b>{claim.formType}</b><span>₹{Number(claim.amount).toLocaleString("en-IN")}</span><small>{claim.purpose}</small></div><div className="timeline">{claim.stages.map((s,i)=>{const done=!!s.exitedAt;return <div className={`timeline-node ${done?"done":s===current?"current":"upcoming"}`} key={s.id}><button onClick={()=>setOpen(open===s.id?null:s.id)}><i /><span><b>{s.stageName}</b><small>{done?`Done · ${days(s)} days`:s===current?`Current · ${days(s)} days`:"Upcoming"}</small></span></button>{open===s.id&&<div className="stage-detail">{s.officerName&&<p><b>{s.officerName}</b> · {s.officerDesignation}<br/>{s.office}</p>}</div>}{s===current&&days(s)>=7&&<div className="escalation-banner">This claim has been at this desk for {days(s)} days. EPFO&apos;s own citizens&apos; charter benchmark is 15–30 working days.<button disabled={busy===claim.id} onClick={async()=>{setBusy(claim.id);const r=await fetch(`/api/claims/${claim.id}/escalate`,{method:"POST"});const d=await r.json();onToast(r.ok?d.message:d.error);setBusy(null);}}>{busy===claim.id?"Escalating…":"Escalate to next officer"}</button></div>}</div>})}</div></article>})}</section>}
