CREATE TYPE "ClaimOutcome" AS ENUM ('PASSED','RETURNED','REJECTED','ESCALATED');
CREATE TYPE "ClaimFaultParty" AS ENUM ('MEMBER','EMPLOYER','EPFO');
CREATE TYPE "ClaimStatus" AS ENUM ('DRAFT','SUBMITTED','IN_PROGRESS','RETURNED','REJECTED','SETTLED');
ALTER TABLE "Claim" ALTER COLUMN "status" TYPE "ClaimStatus" USING CASE "status" WHEN 'UNDER_PROCESS' THEN 'IN_PROGRESS' ELSE "status" END::"ClaimStatus";
ALTER TABLE "Claim" ADD COLUMN "correctionRound" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "cumulativeDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ClaimStage" ADD COLUMN "outcome" "ClaimOutcome", ADD COLUMN "reasonCode" TEXT, ADD COLUMN "reasonNote" TEXT, ADD COLUMN "evidenceRef" TEXT, ADD COLUMN "faultParty" "ClaimFaultParty";
